project:
    name: gh_ext
    number: 11
    owner: scooter-indie
repositories:
    - scooter-indie/gh_ext
defaults:
    priority: p2
    status: backlog
    labels:
        - pm-tracked
fields:
    priority:
        field: Priority
        values:
            p0: P0
            p1: P1
            p2: P2
    status:
        field: Status
        values:
            backlog: Backlog
            done: Done
            in_progress: In progress
            in_review: In review
            ready: Ready
triage:
    estimate:
        query: is:issue is:open -has:estimate
        apply: {}
        interactive:
            estimate: true
    tracked:
        query: is:issue is:open -label:pm-tracked
        apply:
            labels:
                - pm-tracked
            fields:
                priority: p1
                status: backlog
        interactive:
            status: true
metadata:
    project:
        id: PVT_kwHOAATLPs4BJeuX
    fields:
        - name: Title
          id: PVTF_lAHOAATLPs4BJeuXzg5oVA0
          data_type: TITLE
        - name: Assignees
          id: PVTF_lAHOAATLPs4BJeuXzg5oVA4
          data_type: ASSIGNEES
        - name: Status
          id: PVTSSF_lAHOAATLPs4BJeuXzg5oVA8
          data_type: SINGLE_SELECT
          options:
            - name: Backlog
              id: f75ad846
            - name: Ready
              id: 61e4505c
            - name: In progress
              id: 47fc9ee4
            - name: In review
              id: df73e18b
            - name: Done
              id: "98236657"
        - name: Labels
          id: PVTF_lAHOAATLPs4BJeuXzg5oVBA
          data_type: LABELS
        - name: Linked pull requests
          id: PVTF_lAHOAATLPs4BJeuXzg5oVBE
          data_type: LINKED_PULL_REQUESTS
        - name: Milestone
          id: PVTF_lAHOAATLPs4BJeuXzg5oVBI
          data_type: MILESTONE
        - name: Repository
          id: PVTF_lAHOAATLPs4BJeuXzg5oVBM
          data_type: REPOSITORY
        - name: Reviewers
          id: PVTF_lAHOAATLPs4BJeuXzg5oVBQ
          data_type: REVIEWERS
        - name: Parent issue
          id: PVTF_lAHOAATLPs4BJeuXzg5oVBU
          data_type: PARENT_ISSUE
        - name: Sub-issues progress
          id: PVTF_lAHOAATLPs4BJeuXzg5oVBY
          data_type: SUB_ISSUES_PROGRESS
        - name: Priority
          id: PVTSSF_lAHOAATLPs4BJeuXzg5oVCs
          data_type: SINGLE_SELECT
          options:
            - name: P0
              id: "79628723"
            - name: P1
              id: 0a877460
            - name: P2
              id: da944a9c
        - name: Size
          id: PVTSSF_lAHOAATLPs4BJeuXzg5oVCw
          data_type: SINGLE_SELECT
          options:
            - name: XS
              id: 6c6483d2
            - name: S
              id: f784b110
            - name: M
              id: 7515a9f1
            - name: L
              id: 817d0097
            - name: XL
              id: db339eb2
        - name: Estimate
          id: PVTF_lAHOAATLPs4BJeuXzg5oVC0
          data_type: NUMBER
        - name: Start date
          id: PVTF_lAHOAATLPs4BJeuXzg5oVC4
          data_type: DATE
        - name: Target date
          id: PVTF_lAHOAATLPs4BJeuXzg5oVC8
          data_type: DATE
