version: 2

project_name: gh-pmu

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: gh-pmu
    main: .
    binary: gh-pmu
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/scooter-indie/gh-pmu/cmd.version={{.Version}}

archives:
  - id: gh-pmu
    formats:
      - binary
    name_template: "{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: scooter-indie
    name: gh-pmu
  prerelease: auto
  name_template: "gh-pmu {{.Version}}"
