version: 2

project_name: gh-pm

before:
  hooks:
    - go mod tidy

builds:
  - id: gh-pm
    main: .
    binary: gh-pm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/scooter-indie/gh-pm/cmd.version={{.Version}}

archives:
  - id: gh-pm
    builds:
      - gh-pm
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: scooter-indie
    name: gh-pm-unified
  draft: false
  prerelease: auto
